// Mocks generated by Mockito 5.4.2 from annotations
// in mottai_flutter_app/test/force_update/force_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_common/src/firestore_documents/force_update_config.dart'
    as _i4;
import 'package:firebase_common/src/firestore_repositories/force_update_config.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ForceUpdateConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForceUpdateConfigRepository extends _i1.Mock
    implements _i2.ForceUpdateConfigRepository {
  MockForceUpdateConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.ReadForceUpdateConfig?> subscribeForceUpdateConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeForceUpdateConfig,
          [],
        ),
        returnValue: _i3.Stream<_i4.ReadForceUpdateConfig?>.empty(),
      ) as _i3.Stream<_i4.ReadForceUpdateConfig?>);
}
