// Mocks generated by Mockito 5.4.2 from annotations
// in mottai_flutter_app/test/todo/ui/todos_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_common/src/firestore_documents/todo.dart' as _i5;
import 'package:firebase_common/src/firestore_repositories/todo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i3.TodoRepository {
  @override
  _i4.Stream<List<_i5.ReadTodo>> subscribeTodos({required bool? descending}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeTodos,
          [],
          {#descending: descending},
        ),
        returnValue: _i4.Stream<List<_i5.ReadTodo>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.ReadTodo>>.empty(),
      ) as _i4.Stream<List<_i5.ReadTodo>>);
  @override
  _i4.Future<_i2.DocumentReference<_i5.CreateTodo>> add({
    required String? title,
    required String? description,
    required DateTime? dueDateTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {
            #title: title,
            #description: description,
            #dueDateTime: dueDateTime,
          },
        ),
        returnValue: _i4.Future<_i2.DocumentReference<_i5.CreateTodo>>.value(
            _FakeDocumentReference_0<_i5.CreateTodo>(
          this,
          Invocation.method(
            #add,
            [],
            {
              #title: title,
              #description: description,
              #dueDateTime: dueDateTime,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentReference<_i5.CreateTodo>>.value(
                _FakeDocumentReference_0<_i5.CreateTodo>(
          this,
          Invocation.method(
            #add,
            [],
            {
              #title: title,
              #description: description,
              #dueDateTime: dueDateTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<_i5.CreateTodo>>);
  @override
  _i4.Future<void> updateCompletionStatus({
    required String? todoId,
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompletionStatus,
          [],
          {
            #todoId: todoId,
            #value: value,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
