// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtU_4OAQdQrNbnUpuSNqQQM4rutOaca8',
    appId: '1:330095859862:android:5426f370655403973ccab7',
    messagingSenderId: '330095859862',
    projectId: 'mottai-app-dev',
    storageBucket: 'mottai-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOhGcC_UIfxqrllhmqjysnr64looOmKrk',
    appId: '1:330095859862:ios:9c5812e81e6862513ccab7',
    messagingSenderId: '330095859862',
    projectId: 'mottai-app-dev',
    storageBucket: 'mottai-app-dev.appspot.com',
    iosClientId: '330095859862-dggicosj8oe26l47aoghlobuuv480ps5.apps.googleusercontent.com',
    iosBundleId: 'com.kosukesaigusa.mottaiFlutterApp.dev',
  );
}
