// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_-jpRLOtS59zlNI1KCufmI4OOwBERkM',
    appId: '1:709197089170:android:ea115cc56387c6c37ed94b',
    messagingSenderId: '709197089170',
    projectId: 'mottai-app-dev-2',
    storageBucket: 'mottai-app-dev-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaXi3WuwG4YgsTwDsHvqXKa6hfpmx77c',
    appId: '1:709197089170:ios:7617a4349b5968e77ed94b',
    messagingSenderId: '709197089170',
    projectId: 'mottai-app-dev-2',
    storageBucket: 'mottai-app-dev-2.appspot.com',
    androidClientId:
        '709197089170-eoscur7kmv2s45ikpgkvdjtim6b6sbgb.apps.googleusercontent.com',
    iosClientId:
        '709197089170-1lr8vaboc73s41u7l2vijfqs2c7udu0n.apps.googleusercontent.com',
    iosBundleId: 'com.kosukesaigusa.mottaiFlutterApp.dev',
  );
}
